### ISSUE TITLE
Finding a good home for backups

### ISSUE THREAD

**Issue by allonhadaya** [inversoft/2016-security-scripts#1]
The backup script in `template/ubuntu-16.04/backup.sh` uses `/tmp/backups` as the destination of backup files (as well as intermediate files).

```sh
BACKUP_DIR=/tmp/backups
```

On some distros `/tmp` is cleared either on boot or by regular cron jobs: http://serverfault.com/questions/377348/when-does-tmp-get-cleared

On other systems `/tmp` is backed by RAM and may be lost on crashes.

This is not the default behaviour on Ubuntu, but should a different directory be chosen in case this script is used on a distro that *does* clear tmp OR if a user happens to configure their Ubuntu server to clear tmp?

Perhaps this is actually a philosophical point: backups are not temporary by definition. They are persistent (at least for the duration of the retention policy).

How about `/root/backups`? Is there an even better option? Is `/tmp` actually the right place; why?

I'm curious to hear your thoughts!

**Comment by voidmain** [comment]
I wrote it this way because the `backup.sh` script is just an example. Also, I put at the bottom of the script a commented out line that would copy the files offsite. My thought was to drop them in `/tmp`, copy them offsite, and then potentially clear `/tmp` or let it be cleared whenever by whoever. I'm up for changing that behavior in the script though.

**Comment by allonhadaya** [comment]
Cool, the choice definitely makes sense in the context of copying the backup files elsewhere. What do you think of #4?

**Comment by voidmain** [comment]
Looks good. I merged it into master. Thanks for the update.
